"""komek table

Revision ID: da271dc5549d
Revises: 
Create Date: 2020-07-06 20:10:50.340828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da271dc5549d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('komek',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=30), nullable=True),
    sa.Column('service', sa.String(length=255), nullable=True),
    sa.Column('is_giver', sa.Boolean(), nullable=True),
    sa.Column('flag', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_komek_city'), 'komek', ['city'], unique=False)
    op.create_index(op.f('ix_komek_name'), 'komek', ['name'], unique=False)
    op.create_index(op.f('ix_komek_phone'), 'komek', ['phone'], unique=False)
    op.create_index(op.f('ix_komek_service'), 'komek', ['service'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_komek_service'), table_name='komek')
    op.drop_index(op.f('ix_komek_phone'), table_name='komek')
    op.drop_index(op.f('ix_komek_name'), table_name='komek')
    op.drop_index(op.f('ix_komek_city'), table_name='komek')
    op.drop_table('komek')
    # ### end Alembic commands ###
